name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Welcome ${{github.actor}} :tada: 
          Thank you for reporting the issue, we'll respond soon.!!
        pr-message: |
          # Welcome ${{github.actor}} :tada: 
          Thank you for the PR!!
          Hang tight it will be merged soon.
